# PooooK Prose Knuckles {#Keyboard-free keyboarding anytime/anywhere. Like brass knuckles for the information age. }

#### Keywords {wearables, touch typing, keyboarding, knuckles}

 With the miniature accelerometers now available, anyone who can touch-type on a keyboard should be able to ditch that hardware and instead compose their prose from any surface at hand: perhaps a lunch counter, a steering wheel, a shelf, or one's own legs. The PooooK Prose Knuckles concept is to embed the necessary circuits into a pair of wearable input devices having the form factor of brass knuckles, but bendy like those Livestrong bracelets. Just pair them with your smartphone, parrot a few sample prompts to train the software, and you're good to go for hours of keyboard-free expression.

## The Keyboard Crutch

It never fails: you finally step out for lunch and then your phone blows up with texts, slack messages, and emails. You spend your "break" only half-conversing with the colleagues you like (while mentally composing responses you can't send to those you don't - until you're back to your desk). Or else you spend the entire time rudely face-down in your black mirror, typing with 1 or 2 fingers at a tenth your normal speed. Few would step out to place a phone call nowadays, especially when such can be so easily overheard by the wrong people, while leaving no traceable/searchable reference for the right people.  

It's not just desk workers who could benefit from board-cutting in addition to cord-cutting. Consider the journalist or scientist out in the field, the doctor already prepped for surgery, the cop out walking the beat. Silently capturing observations or executing precise searches - just-in-time - could be invaluable.

Let's kick our species' reliance on keyboards to the curb. Someday soon, they're going to look about as antiquated as the punch card.


## Kicking the Keyboard Habit

Building on the [Ring GINA wearable computer interaction devices](/http://www-bsac.eecs.berkeley.edu/publications/search/send_publication_pdf2client.php?pubID=1381271517) developed by Joseph Greenspun and Kristofer S. J. Pister of UC Berkeley's Department of Electrical Engineering and Computer Science, the PooooK flexible knuckle-sets would first be 3D printed and accelerometers, Bluetooth connectors, and batteries would be inserted with hand-assembly.  

Prototype users with measurably-strong QWERTY and/or Dvorak touch-typing skills would be needed to assist with the machine learning portion of the project. Inputs of known alphanumeric characters, words and other strings would be taught from a spectrum of surfaces including hard and soft flat horizontal and vertical expanses to surfaces with curvature (like legs and steering wheels). In all cases, users would be training their own personalized input algorithms, and patterns detected by the team could become part of a base common denominator algorithm (to make training requirements shorter for each generation of user: alpha, beta, etc.).  

## The Post-Keyboard Era

Once we're free of keyboards, we can get out into the world more and record better the truth of what we find, as well as what we think about it. Who hasn't taken a hike, freeing the mind to bring forth the answer to a pressing problem? Similar to going wireless, going keyboard-less will free us to communicate more widely - yet more precisely.

In addition, there are millions of people for whom smartphones are their only means of connection to the information age. Without full-size keyboard hardware to make composition easy and efficient, it's possible that some feel relegated to the role of information accessors, not as much information contributors. It's time we stopped missing out on their contributions. Inexpensive wearable input devices could bring us all closer to the global community we deserve.
